'use strict';
// Cross-language golden-equivalence harness (Task 2.1). Both this file and
// repo_radar/tests/test_activity_golden.py read the SAME two committed fixtures
// (golden-cases.json / golden-expected.jsonl, generated once from the authoritative Python
// encoder via `python -m repo_radar.activity._gen_golden`) and assert byte-equality, so neither
// encoder can drift silently.
const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');
const { buildRecord, encodeRecord } = require('../records');

const D = __dirname;
const cases = JSON.parse(fs.readFileSync(path.join(D, 'golden-cases.json'), 'utf8'));
const expected = fs.readFileSync(path.join(D, 'golden-expected.jsonl'), 'utf8').split('\n');

test('node encodes every record type byte-for-byte (Unicode + numeric edge cases)', () => {
  cases.forEach((c, i) => {
    const line = encodeRecord(buildRecord(c.type, c.args)).toString('utf8');
    assert.strictEqual(line, expected[i] + '\n', `case ${i} (${c.type}) diverged from the Python golden encoding`);
  });
});

// Step 5b: truncation parity. `golden-truncation.json` = { input, expected_line }, generated by
// the SAME Python helper from an event carrying a genuinely oversized (>1 KiB), entirely
// multibyte value. The fixed metadata below (activity_id/ts/seq/event/field key) MUST match
// repo_radar/activity/_gen_golden.py's TRUNCATION_* constants exactly, since only {input,
// expected_line} are committed -- both languages independently rebuild the surrounding record.
test('node truncation matches the committed Python golden line byte-for-byte, on a UTF-8 boundary', () => {
  const { MAX_VALUE_BYTES } = require('../records');
  const trunc = JSON.parse(fs.readFileSync(path.join(D, 'golden-truncation.json'), 'utf8'));

  const rec = buildRecord('event', {
    seq: 100,
    activity_id: '00000000-0000-4000-8000-000000000000',
    ts: '2026-08-14T00:00:00-07:00',
    level: 'info',
    event: 'oversized_value',
    fields: { blob: trunc.input },
  });

  const line = encodeRecord(rec).toString('utf8');
  assert.strictEqual(line, trunc.expected_line, 'truncated encoding diverged from the Python golden line');
  assert.strictEqual(rec._truncated, true);
  const stored = rec.fields.blob;
  assert.ok(Buffer.byteLength(stored, 'utf8') <= MAX_VALUE_BYTES, 'truncated value must fit MAX_VALUE_BYTES');
  assert.ok(stored.includes('[truncated'), 'truncated value must carry the visible marker');
  // A byte-exact match against the committed golden line (produced by the Python encoder on the
  // SAME oversized input) already implies the cut landed on a valid UTF-8 boundary -- a
  // mid-sequence split would have produced different, non-matching bytes above.
});
